---
# tasks file for cluster_destroy

- name: Ensure requirements in place
  package:
    name:
      - libguestfs-tools
      - guestfs-tools
      - qemu-kvm
      - python3-libvirt
    state: present
  become: yes

- name: All tasks with destroying a VM
  block:

  - name: Get VMs list
    community.libvirt.virt:
      command: list_vms
    register: existing_vms
    changed_when: no

  - name: Destroy listed VMs
    community.libvirt.virt:
      command: destroy
      name: "{{ vm_name }}"

  - name: Undefine listed VM
    community.libvirt.virt:
      command: undefine
      name: "{{ vm_name }}"

  when: "vm_name in existing_vms.list_vms"
